platform :ios, '8.0'
target 'HLCommon' do
pod 'AFNetworking', '~> 3.1.0'
pod 'Masonry'
pod 'SDWebImage'
pod 'ReactiveCocoa','2.5'
pod 'MJExtension'
pod 'MJRefresh'
pod 'YYText'
pod 'YYWebImage'
pod 'MBProgressHUD'
end
